language: node_js

node_js: '6.10'

cache:
  directories:
  - node_modules

install:
- npm install
- npm run lint

script: npm test

deploy:
  provider: npm
  email: commits@codemy.fun
  api_key: $NPM_DEPLOY_TOKEN
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
